// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: careerhub/review_service/restapi/restapi_grpc/review.proto

package restapi_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReviewReaderGrpcClient is the client API for ReviewReaderGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReviewReaderGrpcClient interface {
	GetCompanyScores(ctx context.Context, in *GetCompanyScoresRequest, opts ...grpc.CallOption) (*GetCompanyScoresResponse, error)
}

type reviewReaderGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewReviewReaderGrpcClient(cc grpc.ClientConnInterface) ReviewReaderGrpcClient {
	return &reviewReaderGrpcClient{cc}
}

func (c *reviewReaderGrpcClient) GetCompanyScores(ctx context.Context, in *GetCompanyScoresRequest, opts ...grpc.CallOption) (*GetCompanyScoresResponse, error) {
	out := new(GetCompanyScoresResponse)
	err := c.cc.Invoke(ctx, "/careerhub.review_service.restapi_grpc.ReviewReaderGrpc/GetCompanyScores", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewReaderGrpcServer is the server API for ReviewReaderGrpc service.
// All implementations must embed UnimplementedReviewReaderGrpcServer
// for forward compatibility
type ReviewReaderGrpcServer interface {
	GetCompanyScores(context.Context, *GetCompanyScoresRequest) (*GetCompanyScoresResponse, error)
	mustEmbedUnimplementedReviewReaderGrpcServer()
}

// UnimplementedReviewReaderGrpcServer must be embedded to have forward compatible implementations.
type UnimplementedReviewReaderGrpcServer struct {
}

func (UnimplementedReviewReaderGrpcServer) GetCompanyScores(context.Context, *GetCompanyScoresRequest) (*GetCompanyScoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompanyScores not implemented")
}
func (UnimplementedReviewReaderGrpcServer) mustEmbedUnimplementedReviewReaderGrpcServer() {}

// UnsafeReviewReaderGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReviewReaderGrpcServer will
// result in compilation errors.
type UnsafeReviewReaderGrpcServer interface {
	mustEmbedUnimplementedReviewReaderGrpcServer()
}

func RegisterReviewReaderGrpcServer(s grpc.ServiceRegistrar, srv ReviewReaderGrpcServer) {
	s.RegisterService(&ReviewReaderGrpc_ServiceDesc, srv)
}

func _ReviewReaderGrpc_GetCompanyScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanyScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewReaderGrpcServer).GetCompanyScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/careerhub.review_service.restapi_grpc.ReviewReaderGrpc/GetCompanyScores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewReaderGrpcServer).GetCompanyScores(ctx, req.(*GetCompanyScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReviewReaderGrpc_ServiceDesc is the grpc.ServiceDesc for ReviewReaderGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReviewReaderGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "careerhub.review_service.restapi_grpc.ReviewReaderGrpc",
	HandlerType: (*ReviewReaderGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCompanyScores",
			Handler:    _ReviewReaderGrpc_GetCompanyScores_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "careerhub/review_service/restapi/restapi_grpc/review.proto",
}
