// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: careerhub/review_service/crawler/crawler_grpc/review.proto

package crawler_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCrawlingTasksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site string `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
}

func (x *GetCrawlingTasksRequest) Reset() {
	*x = GetCrawlingTasksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCrawlingTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCrawlingTasksRequest) ProtoMessage() {}

func (x *GetCrawlingTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCrawlingTasksRequest.ProtoReflect.Descriptor instead.
func (*GetCrawlingTasksRequest) Descriptor() ([]byte, []int) {
	return file_careerhub_review_service_crawler_crawler_grpc_review_proto_rawDescGZIP(), []int{0}
}

func (x *GetCrawlingTasksRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

type GetCrawlingTasksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompanyNames []string `protobuf:"bytes,1,rep,name=companyNames,proto3" json:"companyNames,omitempty"`
}

func (x *GetCrawlingTasksResponse) Reset() {
	*x = GetCrawlingTasksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCrawlingTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCrawlingTasksResponse) ProtoMessage() {}

func (x *GetCrawlingTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCrawlingTasksResponse.ProtoReflect.Descriptor instead.
func (*GetCrawlingTasksResponse) Descriptor() ([]byte, []int) {
	return file_careerhub_review_service_crawler_crawler_grpc_review_proto_rawDescGZIP(), []int{1}
}

func (x *GetCrawlingTasksResponse) GetCompanyNames() []string {
	if x != nil {
		return x.CompanyNames
	}
	return nil
}

type SetScoreNPageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site           string `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	CompanyName    string `protobuf:"bytes,2,opt,name=companyName,proto3" json:"companyName,omitempty"`
	AvgScore       int32  `protobuf:"varint,3,opt,name=avgScore,proto3" json:"avgScore,omitempty"`
	TotalPageCount int32  `protobuf:"varint,4,opt,name=totalPageCount,proto3" json:"totalPageCount,omitempty"`
	PageSize       int32  `protobuf:"varint,5,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *SetScoreNPageRequest) Reset() {
	*x = SetScoreNPageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetScoreNPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetScoreNPageRequest) ProtoMessage() {}

func (x *SetScoreNPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetScoreNPageRequest.ProtoReflect.Descriptor instead.
func (*SetScoreNPageRequest) Descriptor() ([]byte, []int) {
	return file_careerhub_review_service_crawler_crawler_grpc_review_proto_rawDescGZIP(), []int{2}
}

func (x *SetScoreNPageRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *SetScoreNPageRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *SetScoreNPageRequest) GetAvgScore() int32 {
	if x != nil {
		return x.AvgScore
	}
	return 0
}

func (x *SetScoreNPageRequest) GetTotalPageCount() int32 {
	if x != nil {
		return x.TotalPageCount
	}
	return 0
}

func (x *SetScoreNPageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SetScoreNPageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SetScoreNPageResponse) Reset() {
	*x = SetScoreNPageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetScoreNPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetScoreNPageResponse) ProtoMessage() {}

func (x *SetScoreNPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetScoreNPageResponse.ProtoReflect.Descriptor instead.
func (*SetScoreNPageResponse) Descriptor() ([]byte, []int) {
	return file_careerhub_review_service_crawler_crawler_grpc_review_proto_rawDescGZIP(), []int{3}
}

func (x *SetScoreNPageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SetNotExistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site        string `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	CompanyName string `protobuf:"bytes,2,opt,name=companyName,proto3" json:"companyName,omitempty"`
}

func (x *SetNotExistRequest) Reset() {
	*x = SetNotExistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetNotExistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNotExistRequest) ProtoMessage() {}

func (x *SetNotExistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNotExistRequest.ProtoReflect.Descriptor instead.
func (*SetNotExistRequest) Descriptor() ([]byte, []int) {
	return file_careerhub_review_service_crawler_crawler_grpc_review_proto_rawDescGZIP(), []int{4}
}

func (x *SetNotExistRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *SetNotExistRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

type SetNotExistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SetNotExistResponse) Reset() {
	*x = SetNotExistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetNotExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNotExistResponse) ProtoMessage() {}

func (x *SetNotExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNotExistResponse.ProtoReflect.Descriptor instead.
func (*SetNotExistResponse) Descriptor() ([]byte, []int) {
	return file_careerhub_review_service_crawler_crawler_grpc_review_proto_rawDescGZIP(), []int{5}
}

func (x *SetNotExistResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetCrawlingPagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site string `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
}

func (x *GetCrawlingPagesRequest) Reset() {
	*x = GetCrawlingPagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCrawlingPagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCrawlingPagesRequest) ProtoMessage() {}

func (x *GetCrawlingPagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCrawlingPagesRequest.ProtoReflect.Descriptor instead.
func (*GetCrawlingPagesRequest) Descriptor() ([]byte, []int) {
	return file_careerhub_review_service_crawler_crawler_grpc_review_proto_rawDescGZIP(), []int{6}
}

func (x *GetCrawlingPagesRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

type GetCrawlingPagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CrawlingPages []*CrawlingPage `protobuf:"bytes,1,rep,name=crawlingPages,proto3" json:"crawlingPages,omitempty"`
}

func (x *GetCrawlingPagesResponse) Reset() {
	*x = GetCrawlingPagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCrawlingPagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCrawlingPagesResponse) ProtoMessage() {}

func (x *GetCrawlingPagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCrawlingPagesResponse.ProtoReflect.Descriptor instead.
func (*GetCrawlingPagesResponse) Descriptor() ([]byte, []int) {
	return file_careerhub_review_service_crawler_crawler_grpc_review_proto_rawDescGZIP(), []int{7}
}

func (x *GetCrawlingPagesResponse) GetCrawlingPages() []*CrawlingPage {
	if x != nil {
		return x.CrawlingPages
	}
	return nil
}

type CrawlingPage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompanyName         string `protobuf:"bytes,1,opt,name=companyName,proto3" json:"companyName,omitempty"`
	CurrentCrawlingPage int32  `protobuf:"varint,2,opt,name=currentCrawlingPage,proto3" json:"currentCrawlingPage,omitempty"`
	PageSize            int32  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *CrawlingPage) Reset() {
	*x = CrawlingPage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrawlingPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlingPage) ProtoMessage() {}

func (x *CrawlingPage) ProtoReflect() protoreflect.Message {
	mi := &file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlingPage.ProtoReflect.Descriptor instead.
func (*CrawlingPage) Descriptor() ([]byte, []int) {
	return file_careerhub_review_service_crawler_crawler_grpc_review_proto_rawDescGZIP(), []int{8}
}

func (x *CrawlingPage) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *CrawlingPage) GetCurrentCrawlingPage() int32 {
	if x != nil {
		return x.CurrentCrawlingPage
	}
	return 0
}

func (x *CrawlingPage) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_careerhub_review_service_crawler_crawler_grpc_review_proto protoreflect.FileDescriptor

var file_careerhub_review_service_crawler_crawler_grpc_review_proto_rawDesc = []byte{
	0x0a, 0x3a, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2f, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x72, 0x61, 0x77, 0x6c,
	0x65, 0x72, 0x2f, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x25, 0x63, 0x61,
	0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x22, 0x2d, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x69,
	0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69,
	0x74, 0x65, 0x22, 0x3e, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x69, 0x6e,
	0x67, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x22, 0xac, 0x01, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4e,
	0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x74, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x76, 0x67, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x76, 0x67, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x26, 0x0a,
	0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x22, 0x2f, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4e, 0x50, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x4a, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2d,
	0x0a, 0x13, 0x53, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2d, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x67, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x74, 0x65, 0x22, 0x75, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x67, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0d, 0x63, 0x72, 0x61, 0x77,
	0x6c, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x33, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c,
	0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x69, 0x6e, 0x67,
	0x50, 0x61, 0x67, 0x65, 0x52, 0x0d, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x69, 0x6e, 0x67, 0x50, 0x61,
	0x67, 0x65, 0x73, 0x22, 0x7e, 0x0a, 0x0c, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x69, 0x6e, 0x67, 0x50,
	0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x13, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x43, 0x72, 0x61, 0x77, 0x6c, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x13, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x61, 0x77, 0x6c,
	0x69, 0x6e, 0x67, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x32, 0xcc, 0x04, 0x0a, 0x0a, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x47, 0x72,
	0x70, 0x63, 0x12, 0x93, 0x01, 0x0a, 0x10, 0x67, 0x65, 0x74, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x69,
	0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x3e, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72,
	0x68, 0x75, 0x62, 0x2e, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3f, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72,
	0x68, 0x75, 0x62, 0x2e, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x73, 0x6b, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x8a, 0x01, 0x0a, 0x0d, 0x73, 0x65, 0x74,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x4e, 0x50, 0x61, 0x67, 0x65, 0x12, 0x3b, 0x2e, 0x63, 0x61, 0x72,
	0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x5f, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4e, 0x50, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3c, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72,
	0x68, 0x75, 0x62, 0x2e, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x53, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x84, 0x01, 0x0a, 0x0b, 0x73, 0x65, 0x74, 0x4e, 0x6f, 0x74,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x12, 0x39, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75,
	0x62, 0x2e, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65,
	0x74, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x3a, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x72, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x72, 0x61, 0x77,
	0x6c, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x93, 0x01, 0x0a,
	0x10, 0x67, 0x65, 0x74, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x67, 0x65,
	0x73, 0x12, 0x3e, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x72, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x72, 0x61,
	0x77, 0x6c, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x72, 0x61,
	0x77, 0x6c, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x3f, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2e, 0x72, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x72, 0x61,
	0x77, 0x6c, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x72, 0x61,
	0x77, 0x6c, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x68, 0x75, 0x62, 0x2f,
	0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63,
	0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_careerhub_review_service_crawler_crawler_grpc_review_proto_rawDescOnce sync.Once
	file_careerhub_review_service_crawler_crawler_grpc_review_proto_rawDescData = file_careerhub_review_service_crawler_crawler_grpc_review_proto_rawDesc
)

func file_careerhub_review_service_crawler_crawler_grpc_review_proto_rawDescGZIP() []byte {
	file_careerhub_review_service_crawler_crawler_grpc_review_proto_rawDescOnce.Do(func() {
		file_careerhub_review_service_crawler_crawler_grpc_review_proto_rawDescData = protoimpl.X.CompressGZIP(file_careerhub_review_service_crawler_crawler_grpc_review_proto_rawDescData)
	})
	return file_careerhub_review_service_crawler_crawler_grpc_review_proto_rawDescData
}

var file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_careerhub_review_service_crawler_crawler_grpc_review_proto_goTypes = []interface{}{
	(*GetCrawlingTasksRequest)(nil),  // 0: careerhub.review_service.crawler_grpc.GetCrawlingTasksRequest
	(*GetCrawlingTasksResponse)(nil), // 1: careerhub.review_service.crawler_grpc.GetCrawlingTasksResponse
	(*SetScoreNPageRequest)(nil),     // 2: careerhub.review_service.crawler_grpc.SetScoreNPageRequest
	(*SetScoreNPageResponse)(nil),    // 3: careerhub.review_service.crawler_grpc.SetScoreNPageResponse
	(*SetNotExistRequest)(nil),       // 4: careerhub.review_service.crawler_grpc.SetNotExistRequest
	(*SetNotExistResponse)(nil),      // 5: careerhub.review_service.crawler_grpc.SetNotExistResponse
	(*GetCrawlingPagesRequest)(nil),  // 6: careerhub.review_service.crawler_grpc.GetCrawlingPagesRequest
	(*GetCrawlingPagesResponse)(nil), // 7: careerhub.review_service.crawler_grpc.GetCrawlingPagesResponse
	(*CrawlingPage)(nil),             // 8: careerhub.review_service.crawler_grpc.CrawlingPage
}
var file_careerhub_review_service_crawler_crawler_grpc_review_proto_depIdxs = []int32{
	8, // 0: careerhub.review_service.crawler_grpc.GetCrawlingPagesResponse.crawlingPages:type_name -> careerhub.review_service.crawler_grpc.CrawlingPage
	0, // 1: careerhub.review_service.crawler_grpc.ReviewGrpc.getCrawlingTasks:input_type -> careerhub.review_service.crawler_grpc.GetCrawlingTasksRequest
	2, // 2: careerhub.review_service.crawler_grpc.ReviewGrpc.setScoreNPage:input_type -> careerhub.review_service.crawler_grpc.SetScoreNPageRequest
	4, // 3: careerhub.review_service.crawler_grpc.ReviewGrpc.setNotExist:input_type -> careerhub.review_service.crawler_grpc.SetNotExistRequest
	6, // 4: careerhub.review_service.crawler_grpc.ReviewGrpc.getCrawlingPages:input_type -> careerhub.review_service.crawler_grpc.GetCrawlingPagesRequest
	1, // 5: careerhub.review_service.crawler_grpc.ReviewGrpc.getCrawlingTasks:output_type -> careerhub.review_service.crawler_grpc.GetCrawlingTasksResponse
	3, // 6: careerhub.review_service.crawler_grpc.ReviewGrpc.setScoreNPage:output_type -> careerhub.review_service.crawler_grpc.SetScoreNPageResponse
	5, // 7: careerhub.review_service.crawler_grpc.ReviewGrpc.setNotExist:output_type -> careerhub.review_service.crawler_grpc.SetNotExistResponse
	7, // 8: careerhub.review_service.crawler_grpc.ReviewGrpc.getCrawlingPages:output_type -> careerhub.review_service.crawler_grpc.GetCrawlingPagesResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_careerhub_review_service_crawler_crawler_grpc_review_proto_init() }
func file_careerhub_review_service_crawler_crawler_grpc_review_proto_init() {
	if File_careerhub_review_service_crawler_crawler_grpc_review_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCrawlingTasksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCrawlingTasksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetScoreNPageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetScoreNPageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetNotExistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetNotExistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCrawlingPagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCrawlingPagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrawlingPage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_careerhub_review_service_crawler_crawler_grpc_review_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_careerhub_review_service_crawler_crawler_grpc_review_proto_goTypes,
		DependencyIndexes: file_careerhub_review_service_crawler_crawler_grpc_review_proto_depIdxs,
		MessageInfos:      file_careerhub_review_service_crawler_crawler_grpc_review_proto_msgTypes,
	}.Build()
	File_careerhub_review_service_crawler_crawler_grpc_review_proto = out.File
	file_careerhub_review_service_crawler_crawler_grpc_review_proto_rawDesc = nil
	file_careerhub_review_service_crawler_crawler_grpc_review_proto_goTypes = nil
	file_careerhub_review_service_crawler_crawler_grpc_review_proto_depIdxs = nil
}
