// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: careerhub/review_service/crawler/crawler_grpc/review.proto

package crawler_grpc

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReviewGrpcClient is the client API for ReviewGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReviewGrpcClient interface {
}

type reviewGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewReviewGrpcClient(cc grpc.ClientConnInterface) ReviewGrpcClient {
	return &reviewGrpcClient{cc}
}

// ReviewGrpcServer is the server API for ReviewGrpc service.
// All implementations must embed UnimplementedReviewGrpcServer
// for forward compatibility
type ReviewGrpcServer interface {
	mustEmbedUnimplementedReviewGrpcServer()
}

// UnimplementedReviewGrpcServer must be embedded to have forward compatible implementations.
type UnimplementedReviewGrpcServer struct {
}

func (UnimplementedReviewGrpcServer) mustEmbedUnimplementedReviewGrpcServer() {}

// UnsafeReviewGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReviewGrpcServer will
// result in compilation errors.
type UnsafeReviewGrpcServer interface {
	mustEmbedUnimplementedReviewGrpcServer()
}

func RegisterReviewGrpcServer(s grpc.ServiceRegistrar, srv ReviewGrpcServer) {
	s.RegisterService(&ReviewGrpc_ServiceDesc, srv)
}

// ReviewGrpc_ServiceDesc is the grpc.ServiceDesc for ReviewGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReviewGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "careerhub.review_service.crawler_grpc.ReviewGrpc",
	HandlerType: (*ReviewGrpcServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "careerhub/review_service/crawler/crawler_grpc/review.proto",
}
